---
- hosts: all
  remote_user: root
  tasks:
    - name: install httpd
      yum: name=httpd state=present
      tags: install
    - name: 配置文件复制
      copy: src=/etc/httpd/conf/httpd.conf dest=/etc/httpd/conf/ backup=yes
      notify: restart httpd
      tags: conf
    - name: start httpd
      tags: service
      service: name=httpd state=started enabled=yes

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted